"""
项目记忆模块

实现 Claude Code 风格的结构化项目记忆机制：
- CLAUDE.md 文件自动生成和维护
- 构建命令学习
- 调试经验积累
- 代码风格偏好
- 跨会话知识持久化
"""

import os
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Any, Set
from dataclasses import dataclass, field
from datetime import datetime
from loguru import logger


@dataclass
class ProjectKnowledge:
    """项目知识条目"""
    category: str           # build, debug, style, architecture, etc.
    content: str            # 知识内容
    confidence: float       # 置信度 (0-1)
    source: str             # 来源 (learned, user_specified, inferred)
    created_at: datetime
    last_used: Optional[datetime] = None
    use_count: int = 0
    examples: List[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """转换为 Markdown 格式"""
        return f"- {self.content}"

    def to_dict(self) -> Dict:
        return {
            "category": self.category,
            "content": self.content,
            "confidence": self.confidence,
            "source": self.source,
            "created_at": self.created_at.isoformat(),
            "use_count": self.use_count,
        }


class ProjectMemoryManager:
    """
    项目记忆管理器

    实现 Claude Code 风格的项目记忆机制：
    - 自动生成和维护 CLAUDE.md
    - 学习构建命令
    - 记录调试经验
    - 保存代码风格偏好
    - 跨会话知识持久化

    特点：
    - 结构化存储（不是向量搜索的模糊匹配）
    - 每次会话开始时完整加载
    - 越用越聪明，形成项目专属知识库
    - 人类可读可编辑
    """

    def __init__(
        self,
        project_root: str = ".",
        memory_file: str = "CLAUDE.md",
        auto_save: bool = True,
    ):
        """
        初始化项目记忆管理器

        Args:
            project_root: 项目根目录
            memory_file: 记忆文件名
            auto_save: 是否自动保存
        """
        self.project_root = Path(project_root)
        self.memory_file = self.project_root / memory_file
        self.auto_save = auto_save
        self._logger = logger.bind(module="ProjectMemoryManager")

        # 知识库
        self._knowledge: Dict[str, List[ProjectKnowledge]] = {
            "build": [],       # 构建命令
            "test": [],        # 测试命令
            "debug": [],       # 调试经验
            "style": [],       # 代码风格
            "architecture": [], # 架构知识
            "pitfalls": [],    # 常见陷阱
            "dependencies": [], # 依赖信息
        }

        # 项目元数据
        self._metadata: Dict[str, Any] = {
            "project_name": "",
            "language": "",
            "framework": "",
            "last_updated": None,
        }

        # 加载现有记忆
        self._load_memory()

    def _load_memory(self):
        """加载现有的项目记忆"""
        if not self.memory_file.exists():
            self._logger.info("No existing project memory found, starting fresh")
            return

        try:
            content = self.memory_file.read_text(encoding='utf-8')
            self._parse_memory_file(content)
            self._logger.info(f"Loaded project memory from {self.memory_file}")
        except Exception as e:
            self._logger.warning(f"Failed to load project memory: {e}")

    def _parse_memory_file(self, content: str):
        """解析记忆文件"""
        current_section = None

        for line in content.split('\n'):
            line = line.strip()

            # 检测章节标题
            if line.startswith('## '):
                section_name = line[3:].strip().lower()
                section_map = {
                    "build commands": "build",
                    "test commands": "test",
                    "debugging tips": "debug",
                    "code style": "style",
                    "architecture": "architecture",
                    "common pitfalls": "pitfalls",
                    "dependencies": "dependencies",
                }
                current_section = section_map.get(section_name)

            # 解析知识条目
            elif line.startswith('- ') and current_section:
                content = line[2:].strip()
                if content:
                    knowledge = ProjectKnowledge(
                        category=current_section,
                        content=content,
                        confidence=1.0,
                        source="user_specified",
                        created_at=datetime.now(),
                    )
                    self._knowledge[current_section].append(knowledge)

    def save_memory(self):
        """保存项目记忆到文件"""
        try:
            content = self._generate_memory_content()
            self.memory_file.write_text(content, encoding='utf-8')
            self._logger.info(f"Saved project memory to {self.memory_file}")
        except Exception as e:
            self._logger.error(f"Failed to save project memory: {e}")

    def _generate_memory_content(self) -> str:
        """生成记忆文件内容"""
        lines = [
            "# Project Memory",
            "",
            f"Auto-generated by Helix-Swarm. Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
        ]

        # 项目信息
        if self._metadata.get("project_name"):
            lines.append(f"**Project**: {self._metadata['project_name']}")
        if self._metadata.get("language"):
            lines.append(f"**Language**: {self._metadata['language']}")
        if self._metadata.get("framework"):
            lines.append(f"**Framework**: {self._metadata['framework']}")
        lines.append("")

        # 各章节
        section_titles = {
            "build": "Build Commands",
            "test": "Test Commands",
            "debug": "Debugging Tips",
            "style": "Code Style",
            "architecture": "Architecture",
            "pitfalls": "Common Pitfalls",
            "dependencies": "Dependencies",
        }

        for section_key, section_title in section_titles.items():
            knowledge_list = self._knowledge.get(section_key, [])
            if knowledge_list:
                lines.append(f"## {section_title}")
                lines.append("")
                for k in knowledge_list:
                    lines.append(k.to_markdown())
                lines.append("")

        return '\n'.join(lines)

    def learn_build_command(self, command: str, success: bool = True):
        """
        学习构建命令

        Args:
            command: 构建命令
            success: 是否成功
        """
        if success:
            # 检查是否已存在
            existing = [k for k in self._knowledge["build"] if k.content == command]
            if not existing:
                knowledge = ProjectKnowledge(
                    category="build",
                    content=command,
                    confidence=1.0,
                    source="learned",
                    created_at=datetime.now(),
                )
                self._knowledge["build"].append(knowledge)
                self._logger.info(f"Learned build command: {command}")

                if self.auto_save:
                    self.save_memory()

    def learn_test_command(self, command: str, success: bool = True):
        """学习测试命令"""
        if success:
            existing = [k for k in self._knowledge["test"] if k.content == command]
            if not existing:
                knowledge = ProjectKnowledge(
                    category="test",
                    content=command,
                    confidence=1.0,
                    source="learned",
                    created_at=datetime.now(),
                )
                self._knowledge["test"].append(knowledge)
                self._logger.info(f"Learned test command: {command}")

                if self.auto_save:
                    self.save_memory()

    def learn_debugging_tip(self, problem: str, solution: str):
        """
        学习调试经验

        Args:
            problem: 问题描述
            solution: 解决方案
        """
        content = f"**Problem**: {problem} → **Solution**: {solution}"

        knowledge = ProjectKnowledge(
            category="debug",
            content=content,
            confidence=0.8,
            source="learned",
            created_at=datetime.now(),
            examples=[problem],
        )
        self._knowledge["debug"].append(knowledge)
        self._logger.info(f"Learned debugging tip: {problem[:50]}...")

        if self.auto_save:
            self.save_memory()

    def learn_code_style(self, rule: str, example: Optional[str] = None):
        """
        学习代码风格

        Args:
            rule: 风格规则
            example: 示例代码
        """
        knowledge = ProjectKnowledge(
            category="style",
            content=rule,
            confidence=0.9,
            source="learned",
            created_at=datetime.now(),
            examples=[example] if example else [],
        )
        self._knowledge["style"].append(knowledge)

        if self.auto_save:
            self.save_memory()

    def learn_architecture(self, description: str):
        """学习架构知识"""
        knowledge = ProjectKnowledge(
            category="architecture",
            content=description,
            confidence=0.9,
            source="learned",
            created_at=datetime.now(),
        )
        self._knowledge["architecture"].append(knowledge)

        if self.auto_save:
            self.save_memory()

    def learn_pitfall(self, pitfall: str, avoid_method: str):
        """
        学习常见陷阱

        Args:
            pitfall: 陷阱描述
            avoid_method: 避免方法
        """
        content = f"**Avoid**: {pitfall} → **Instead**: {avoid_method}"

        knowledge = ProjectKnowledge(
            category="pitfalls",
            content=content,
            confidence=0.9,
            source="learned",
            created_at=datetime.now(),
        )
        self._knowledge["pitfalls"].append(knowledge)

        if self.auto_save:
            self.save_memory()

    def add_user_knowledge(self, category: str, content: str):
        """
        添加用户指定的知识

        Args:
            category: 类别
            content: 内容
        """
        if category not in self._knowledge:
            self._knowledge[category] = []

        knowledge = ProjectKnowledge(
            category=category,
            content=content,
            confidence=1.0,
            source="user_specified",
            created_at=datetime.now(),
        )
        self._knowledge[category].append(knowledge)

        if self.auto_save:
            self.save_memory()

    def get_knowledge(self, category: Optional[str] = None) -> List[ProjectKnowledge]:
        """
        获取知识

        Args:
            category: 类别（可选）

        Returns:
            List[ProjectKnowledge]: 知识列表
        """
        if category:
            return self._knowledge.get(category, [])

        all_knowledge = []
        for knowledge_list in self._knowledge.values():
            all_knowledge.extend(knowledge_list)
        return all_knowledge

    def get_context_prompt(self) -> str:
        """
        获取项目上下文提示词（用于注入到 LLM）

        Returns:
            str: 上下文提示词
        """
        prompt_parts = ["## Project Context\n"]

        if self._metadata.get("project_name"):
            prompt_parts.append(f"Project: {self._metadata['project_name']}")

        # 构建命令
        build_commands = self._knowledge.get("build", [])
        if build_commands:
            prompt_parts.append("\n### Build Commands")
            for k in build_commands:
                prompt_parts.append(f"- {k.content}")

        # 测试命令
        test_commands = self._knowledge.get("test", [])
        if test_commands:
            prompt_parts.append("\n### Test Commands")
            for k in test_commands:
                prompt_parts.append(f"- {k.content}")

        # 代码风格
        style_rules = self._knowledge.get("style", [])
        if style_rules:
            prompt_parts.append("\n### Code Style")
            for k in style_rules[:5]:  # 最多 5 条
                prompt_parts.append(f"- {k.content}")

        # 常见陷阱
        pitfalls = self._knowledge.get("pitfalls", [])
        if pitfalls:
            prompt_parts.append("\n### Common Pitfalls")
            for k in pitfalls[:3]:  # 最多 3 条
                prompt_parts.append(f"- {k.content}")

        return '\n'.join(prompt_parts)

    def set_project_metadata(self, **kwargs):
        """设置项目元数据"""
        self._metadata.update(kwargs)
        if self.auto_save:
            self.save_memory()

    def get_statistics(self) -> Dict[str, int]:
        """获取统计信息"""
        return {
            category: len(knowledge_list)
            for category, knowledge_list in self._knowledge.items()
        }

    def clear(self):
        """清空所有记忆"""
        for category in self._knowledge:
            self._knowledge[category] = []
        self._metadata = {
            "project_name": "",
            "language": "",
            "framework": "",
            "last_updated": None,
        }
        if self.auto_save:
            self.save_memory()


class AutoMemoryExtractor:
    """
    自动记忆提取器

    从对话和操作中自动提取项目知识。
    """

    def __init__(self, memory_manager: ProjectMemoryManager):
        """
        初始化自动记忆提取器

        Args:
            memory_manager: 项目记忆管理器
        """
        self.memory_manager = memory_manager
        self._logger = logger.bind(module="AutoMemoryExtractor")

    def extract_from_command(self, command: str, output: str, success: bool):
        """
        从命令执行中提取知识

        Args:
            command: 执行的命令
            output: 命令输出
            success: 是否成功
        """
        # 检测构建命令
        build_patterns = [
            r"pip install",
            r"npm install",
            r"yarn install",
            r"cargo build",
            r"make",
            r"cmake",
            r"gradle",
            r"mvn",
        ]

        for pattern in build_patterns:
            if re.search(pattern, command):
                self.memory_manager.learn_build_command(command, success)
                break

        # 检测测试命令
        test_patterns = [
            r"pytest",
            r"unittest",
            r"npm test",
            r"cargo test",
            r"go test",
        ]

        for pattern in test_patterns:
            if re.search(pattern, command):
                self.memory_manager.learn_test_command(command, success)
                break

        # 检测错误和解决方案
        if not success and "error" in output.lower():
            self._extract_debugging_knowledge(command, output)

    def _extract_debugging_knowledge(self, command: str, output: str):
        """提取调试知识"""
        # 提取错误类型
        error_patterns = [
            (r"ImportError: (.+)", "Import error"),
            (r"ModuleNotFoundError: (.+)", "Module not found"),
            (r"SyntaxError: (.+)", "Syntax error"),
            (r"TypeError: (.+)", "Type error"),
            (r"AttributeError: (.+)", "Attribute error"),
            (r"FileNotFoundError: (.+)", "File not found"),
        ]

        for pattern, error_type in error_patterns:
            match = re.search(pattern, output)
            if match:
                problem = f"{error_type}: {match.group(1)[:100]}"
                # 这里可以进一步分析是否找到了解决方案
                # 暂时只记录问题
                self._logger.info(f"Detected error: {problem}")
                break

    def extract_from_file_operation(self, operation: str, path: str, success: bool):
        """
        从文件操作中提取知识

        Args:
            operation: 操作类型
            path: 文件路径
            success: 是否成功
        """
        # 学习项目结构
        if success and operation == "read":
            ext = Path(path).suffix
            if ext == ".py":
                self.memory_manager.set_project_metadata(language="Python")
            elif ext in (".js", ".ts"):
                self.memory_manager.set_project_metadata(language="JavaScript/TypeScript")
            elif ext == ".rs":
                self.memory_manager.set_project_metadata(language="Rust")


# 全局实例
project_memory = ProjectMemoryManager()
auto_memory_extractor = AutoMemoryExtractor(project_memory)
